// <auto-generated />
using System;
using Devlabs.AcTiming.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Devlabs.AcTiming.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AcTimingDbContext))]
    partial class AcTimingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Devlabs.AcTiming.Domain.Shared.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Skin")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("Devlabs.AcTiming.Domain.Shared.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("Devlabs.AcTiming.Domain.Shared.Lap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cuts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DriverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LapTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SectorTimesMs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("DriverId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TrackId");

                    b.ToTable("Lap");
                });

            modelBuilder.Entity("Devlabs.AcTiming.Domain.Shared.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmbientTemp")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LapLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoadTemp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeLimitMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("Devlabs.AcTiming.Domain.Shared.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Config")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Config")
                        .IsUnique();

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Devlabs.AcTiming.Domain.Shared.TrackConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrackId")
                        .IsUnique();

                    b.ToTable("TrackConfigs");
                });

            modelBuilder.Entity("DriverSession", b =>
                {
                    b.Property<int>("DriversId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DriversId", "SessionsId");

                    b.HasIndex("SessionsId");

                    b.ToTable("DriverSession");
                });

            modelBuilder.Entity("Devlabs.AcTiming.Domain.Shared.Lap", b =>
                {
                    b.HasOne("Devlabs.AcTiming.Domain.Shared.Car", "Car")
                        .WithMany("Laps")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Devlabs.AcTiming.Domain.Shared.Driver", "Driver")
                        .WithMany("Laps")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Devlabs.AcTiming.Domain.Shared.Session", "Session")
                        .WithMany("Laps")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Devlabs.AcTiming.Domain.Shared.Track", "Track")
                        .WithMany("Laps")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Driver");

                    b.Navigation("Session");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Devlabs.AcTiming.Domain.Shared.Session", b =>
                {
                    b.HasOne("Devlabs.AcTiming.Domain.Shared.Track", "Track")
                        .WithMany("Sessions")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Devlabs.AcTiming.Domain.Shared.TrackConfig", b =>
                {
                    b.HasOne("Devlabs.AcTiming.Domain.Shared.Track", "Track")
                        .WithOne("TrackConfig")
                        .HasForeignKey("Devlabs.AcTiming.Domain.Shared.TrackConfig", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Devlabs.AcTiming.Domain.Shared.PitLaneDefinition", "PitLane", b1 =>
                        {
                            b1.Property<int>("TrackConfigId");

                            b1.Property<float>("HalfWidthMeters");

                            b1.HasKey("TrackConfigId");

                            b1.ToTable("TrackConfigs");

                            b1
                                .ToJson("PitLane")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("TrackConfigId");

                            b1.OwnsMany("Devlabs.AcTiming.Domain.Shared.WorldPoint", "CenterLine", b2 =>
                                {
                                    b2.Property<int>("PitLaneDefinitionTrackConfigId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<float>("X");

                                    b2.Property<float>("Z");

                                    b2.HasKey("PitLaneDefinitionTrackConfigId", "__synthesizedOrdinal");

                                    b2.ToTable("TrackConfigs");

                                    b2.WithOwner()
                                        .HasForeignKey("PitLaneDefinitionTrackConfigId");
                                });

                            b1.Navigation("CenterLine");
                        });

                    b.OwnsMany("Devlabs.AcTiming.Domain.Shared.SpeedTrapDefinition", "SpeedTraps", b1 =>
                        {
                            b1.Property<int>("TrackConfigId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.HasKey("TrackConfigId", "__synthesizedOrdinal");

                            b1.ToTable("TrackConfigs");

                            b1
                                .ToJson("SpeedTraps")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("TrackConfigId");

                            b1.OwnsOne("Devlabs.AcTiming.Domain.Shared.WorldPoint", "Point1", b2 =>
                                {
                                    b2.Property<int>("SpeedTrapDefinitionTrackConfigId");

                                    b2.Property<int>("SpeedTrapDefinition__synthesizedOrdinal");

                                    b2.Property<float>("X");

                                    b2.Property<float>("Z");

                                    b2.HasKey("SpeedTrapDefinitionTrackConfigId", "SpeedTrapDefinition__synthesizedOrdinal");

                                    b2.ToTable("TrackConfigs");

                                    b2.WithOwner()
                                        .HasForeignKey("SpeedTrapDefinitionTrackConfigId", "SpeedTrapDefinition__synthesizedOrdinal");
                                });

                            b1.OwnsOne("Devlabs.AcTiming.Domain.Shared.WorldPoint", "Point2", b2 =>
                                {
                                    b2.Property<int>("SpeedTrapDefinitionTrackConfigId");

                                    b2.Property<int>("SpeedTrapDefinition__synthesizedOrdinal");

                                    b2.Property<float>("X");

                                    b2.Property<float>("Z");

                                    b2.HasKey("SpeedTrapDefinitionTrackConfigId", "SpeedTrapDefinition__synthesizedOrdinal");

                                    b2.ToTable("TrackConfigs");

                                    b2.WithOwner()
                                        .HasForeignKey("SpeedTrapDefinitionTrackConfigId", "SpeedTrapDefinition__synthesizedOrdinal");
                                });

                            b1.Navigation("Point1")
                                .IsRequired();

                            b1.Navigation("Point2")
                                .IsRequired();
                        });

                    b.Navigation("PitLane");

                    b.Navigation("SpeedTraps");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("DriverSession", b =>
                {
                    b.HasOne("Devlabs.AcTiming.Domain.Shared.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriversId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Devlabs.AcTiming.Domain.Shared.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Devlabs.AcTiming.Domain.Shared.Car", b =>
                {
                    b.Navigation("Laps");
                });

            modelBuilder.Entity("Devlabs.AcTiming.Domain.Shared.Driver", b =>
                {
                    b.Navigation("Laps");
                });

            modelBuilder.Entity("Devlabs.AcTiming.Domain.Shared.Session", b =>
                {
                    b.Navigation("Laps");
                });

            modelBuilder.Entity("Devlabs.AcTiming.Domain.Shared.Track", b =>
                {
                    b.Navigation("Laps");

                    b.Navigation("Sessions");

                    b.Navigation("TrackConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
